//Die Kraken API gibt teilweise besondere Bezeichnungen für die Cryptowährungspaare wieder. Diese müssen hier hinterlegt werden, da sonst null angezeigt wird.
//
// https://api.kraken.com/0/public/AssetPairs
//

//Paar aussuchen und mit der oberen Adresse auf Rückgabewert prüfen; 
//sofern Paar nicht mit Rückgabewert übereinstimmt, diesen in der Funktion hinterlegen

//1INCHEUR,1INCHUSD,AAVEAUD,AAVEETH,AAVEEUR,AAVEGBP,AAVEUSD,AAVEXBT,ADAAUD,ADAETH,ADAEUR,ADAGBP,ADAUSD,ADAUSDT,ADAXBT,ALGOETH,
//ALGOEUR,ALGOGBP,ALGOUSD,ALGOXBT,ANKREUR,ANKRGBP,ANKRUSD,ANKRXBT,ANTETH,ANTEUR,ANTUSD,ANTXBT,ATOMAUD,ATOMETH,ATOMEUR,ATOMGBP,
//ATOMUSD,ATOMXBT,AUDJPY,AUDUSD,AXSEUR,AXSUSD,BADGEREUR,BADGERUSD,BALETH,BALEUR,BALUSD,BALXBT,BANDEUR,BANDUSD,BATETH,BATEUR,
//BATUSD,BATXBT,BCHAUD,BCHETH,BCHEUR,BCHGBP,BCHJPY,BCHUSD,BCHUSDT,BCHXBT,BNTEUR,BNTGBP,BNTUSD,BNTXBT,CHZEUR,CHZUSD,COMPETH,
//COMPEUR,COMPUSD,COMPXBT,CQTEUR,CQTUSD,CRVETH,CRVEUR,CRVUSD,CRVXBT,CTSIEUR,CTSIUSD,DAIEUR,DAIUSD,DAIUSDT,DASHEUR,DASHUSD,
//DASHXBT,DOTAUD,DOTETH,DOTEUR,DOTGBP,DOTUSD,DOTUSDT,DOTXBT,ENJEUR,ENJGBP,ENJUSD,ENJXBT,EOSETH,EOSEUR,EOSUSD,EOSUSDT,EOSXBT,
//ETCETH,ETCEUR,ETCUSD,ETCXBT,ETHAUD,ETHCAD,ETHCHF,ETHDAI,ETHEUR,ETHGBP,ETHJPY,ETHUSD,ETHUSDC,ETHUSDT,ETHXBT,EURAUD,EURCAD,
//EURCHF,EURGBP,EURJPY,EURUSD,EWTEUR,EWTGBP,EWTUSD,EWTXBT,FILAUD,FILETH,FILEUR,FILGBP,FILUSD,FILXBT,FLOWETH,FLOWEUR,FLOWGBP,
//FLOWUSD,FLOWXBT,GBPUSD,GHSTEUR,GHSTGBP,GHSTUSD,GHSTXBT,GNOETH,GNOEUR,GNOUSD,GNOXBT,GRTAUD,GRTETH,GRTEUR,GRTGBP,GRTUSD,GRTXBT,
//ICXETH,ICXEUR,ICXUSD,ICXXBT,INJEUR,INJUSD,KAREUR,KARUSD,KAVAETH,KAVAEUR,KAVAUSD,KAVAXBT,KEEPETH,KEEPEUR,KEEPUSD,KEEPXBT,KNCETH,
//KNCEUR,KNCUSD,KNCXBT,KSMAUD,KSMDOT,KSMETH,KSMEUR,KSMGBP,KSMUSD,KSMXBT,LINKAUD,LINKETH,LINKEUR,LINKGBP,LINKUSD,LINKUSDT,LINKXBT,
//LPTEUR,LPTGBP,LPTUSD,LPTXBT,LRCEUR,LRCUSD,LSKETH,LSKEUR,LSKUSD,LSKXBT,LTCAUD,LTCETH,LTCEUR,LTCGBP,LTCJPY,LTCUSD,LTCUSDT,LTCXBT,
//MANAETH,MANAEUR,MANAUSD,MANAXBT,MATICEUR,MATICGBP,MATICUSD,MATICXBT,MINAEUR,MINAGBP,MINAUSD,MINAXBT,MIREUR,MIRUSD,MKREUR,MKRGBP,
//MKRUSD,MKRXBT,MLNETH,MLNEUR,MLNUSD,MLNXBT,NANOETH,NANOEUR,NANOUSD,NANOXBT,OCEANEUR,OCEANGBP,OCEANUSD,OCEANXBT,OGNEUR,OGNUSD,OMGETH,
//OMGEUR,OMGUSD,OMGXBT,OXTETH,OXTEUR,OXTUSD,OXTXBT,PAXGETH,PAXGEUR,PAXGUSD,PAXGXBT,PERPEUR,PERPUSD,QTUMETH,QTUMEUR,QTUMUSD,QTUMXBT,
//RARIEUR,RARIGBP,RARIUSD,RARIXBT,RENEUR,RENGBP,RENUSD,RENXBT,REPETH,REPEUR,REPUSD,REPV2ETH,REPV2EUR,REPV2USD,REPV2XBT,REPXBT,SANDEUR,
//SANDGBP,SANDUSD,SANDXBT,SCETH,SCEUR,SCUSD,SCXBT,SNXAUD,SNXETH,SNXEUR,SNXGBP,SNXUSD,SNXXBT,SOLEUR,SOLGBP,SOLUSD,SOLXBT,SRMEUR,SRMGBP,
//SRMUSD,SRMXBT,STORJETH,STORJEUR,STORJUSD,STORJXBT,SUSHIEUR,SUSHIGBP,SUSHIUSD,SUSHIXBT,TBTCETH,TBTCEUR,TBTCUSD,TBTCXBT,TRXETH,TRXEUR,
//TRXUSD,TRXXBT,UNIETH,UNIEUR,UNIUSD,UNIXBT,USDCAD,USDCAUD,USDCEUR,USDCGBP,USDCHF,USDCUSD,USDCUSDT,USDJPY,USDTAUD,USDTCAD,USDTCHF,
//USDTEUR,USDTGBP,USDTJPY,USDTUSD,WAVESETH,WAVESEUR,WAVESUSD,WAVESXBT,WBTCEUR,WBTCUSD,XBTAUD,XBTCAD,XBTCHF,XBTDAI,XBTEUR,XBTGBP,XBTJPY,
//XBTUSD,XBTUSDC,XBTUSDT,XDGEUR,XDGUSD,XDGUSDT,XDGXBT,XLMAUD,XLMEUR,XLMGBP,XLMUSD,XLMXBT,XMREUR,XMRUSD,XMRXBT,XRPAUD,XRPCAD,XRPETH,
//XRPEUR,XRPGBP,XRPJPY,XRPUSD,XRPUSDT,XRPXBT,XTZAUD,XTZETH,XTZEUR,XTZGBP,XTZUSD,XTZXBT,YFIAUD,YFIETH,YFIEUR,YFIGBP,YFIUSD,YFIXBT,
//ZECEUR,ZECUSD,ZECXBT,ZRXEUR,ZRXGBP,ZRXUSD,ZRXXBT

String getCryptoShort(String pair){
  if(pair == "BTCEUR"){
    return "XXBTZEUR";
  }else if(pair == "ETHEUR"){
    return "XETHZEUR";
  }else if(pair == "XRPEUR"){
    return "XXRPZEUR";
  }else if(pair == "XLMEUR"){
    return "XXLMZEUR";
  }else if(pair == "ETCEUR"){
    return "XETCZEUR";
  }else if(pair == "XMREUR"){
    return "XXMRZEUR";
  }else{
    return pair;
  }
}
